approvals_reviewer = "auto_review"

[plugins."github@openai-curated"]
enabled = true

[tui]
vim_mode_default = true

[tui.keymap.chat]
edit_queued_message = ["ctrl-up", "ctrl-left"]
increase_reasoning_effort = "alt-."
