windowrule = float off, match:class ^(steam|steam.*)$

windowrule = match:class ^(UnrealEditor)$, no_initial_focus on
windowrule = match:class ^(UnrealEditor)$, no_anim on
windowrule = match:class ^(UnrealEditor)$, suppress_event activate
windowrule = match:class ^(UnrealEditor)$, float off

xwayland {
  force_zero_scaling = true
}
